### ISSUE TITLE
很不错，但问题还是比较多

### ISSUE THREAD

**Issue by lonee8** [fjcqv/wsmud_plugins#1]
好多地方没加延时，NPC还没刷出来，动作指令就发出去了，没取到正确的NPC 或者物品 ID。
毕竟 0.06嘛，期望继续完善。

**Comment by fjcqv** [comment]
这个npc没刷出来不影响指令发出，指令通过websocket送出。都是在服务器端处理。
没取到正确的NPC 或者物品 ID 是因为NPC被杀了，或者服务器重启，物品ID会重新生成，因为无法直接读取到ID。必须右键更新下NPCID和物品ID才行，物品ID在对应商店打开购买窗口更新才行。

**Comment by fjcqv** [comment]
最新版加入部分你的代码 @lonee8

**Comment by lonee8** [comment]
https://gitee.com/hzlqt/wsmud-userscript
这里有些功能不错，自动打BOSS，自动喜宴，自动师门（不用右键更新ID）
可以参考一下。

**Comment by fjcqv** [comment]
看了下，主要使用unsafewindow获取到了页面的websocket，之前我一直奇怪这个怎么用脚本抓取。
现在试下。

**Comment by lonee8** [comment]
他那个功能太乱了，还是你这个规划得好。把好的功能学习过来就OK了。
😆

**Comment by lonee8** [comment]
可惜我不会js，不然也可以帮着写写。

**Comment by a116114** [comment]
请问可以后续加入更多功能吧 有没有联系方式

**Comment by zhangcheele** [comment]
l老哥，怎么用呢 昨天找到猴油脚本的下载地址了 今天找不到了。。
